"""Builds fig6-case-study-validation.png: one of the CO3D teddybear input
photographs next to the reconstructed-and-refined mesh, so the qualitative
result can be judged against what the subject actually looks like.

Requires matplotlib + Pillow. Run from anywhere; writes into figures/ next to
this script. Source images live in outputs/ and are not regenerated by this
script -- swap them there if the case study changes.
"""

import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import image as mpimg

os.chdir(os.path.dirname(os.path.abspath(__file__)))

plt.rcParams["font.family"] = "serif"
plt.rcParams["font.serif"] = ["Georgia", "Times New Roman", "DejaVu Serif"]

input_img = mpimg.imread("outputs/teddy.jpeg")
render_img = mpimg.imread("outputs/blender-output.png")
aspect_a = input_img.shape[1] / input_img.shape[0]
aspect_b = render_img.shape[1] / render_img.shape[0]

# Panels sit side by side (a | b), not stacked. Both source images are
# landscape (~1.73 w/h), so stacking them gave a figure ~4.4 in tall at
# \columnwidth -- close to half a column for two small photographs. A row
# prints ~1.2 in for the same content. It also raises the effective
# resolution of the input photograph, which is only 238 px wide: at 3.3 in
# it printed at ~72 dpi, at 1.65 in it prints at ~145 dpi.
fig_w = 3.5
side_margin, top_margin, bottom_margin, gap, title_h = 0.04, 0.03, 0.04, 0.08, 0.17
img_w = (fig_w - 2 * side_margin - gap) / 2
height_a = img_w / aspect_a
height_b = img_w / aspect_b
row_h = max(height_a, height_b)
fig_h = top_margin + row_h + title_h + bottom_margin

fig = plt.figure(figsize=(fig_w, fig_h), dpi=600)

# Laid out left to right in figure coordinates. Each panel keeps its own
# image's aspect ratio and is centred in the shared row height, so the two
# captions still line up along one baseline beneath the row.
y_row = bottom_margin + title_h
specs = [
    (side_margin, height_a, input_img, "(a) input capture (1 of 8 views)"),
    (side_margin + img_w + gap, height_b, render_img, "(b) reconstructed + refined mesh"),
]
for x_in, h_in, img, title in specs:
    y_in = y_row + (row_h - h_in) / 2
    ax = fig.add_axes([x_in / fig_w, y_in / fig_h, img_w / fig_w, h_in / fig_h])
    ax.imshow(img)
    ax.set_xticks([])
    ax.set_yticks([])
    for s in ax.spines.values():
        s.set_edgecolor("#94a3b8")
        s.set_linewidth(0.8)
    fig.text(
        (x_in + img_w / 2) / fig_w,
        (bottom_margin + title_h / 2) / fig_h,
        title,
        ha="center",
        va="center",
        fontsize=6,
        color="#0f172a",
    )

fig.savefig("figures/fig6-case-study-validation.png", dpi=600, facecolor="white")
plt.close(fig)
print("wrote figures/fig6-case-study-validation.png (side by side)")
